# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Hero: A Roguelike'
description: >
  This project is a roguelike built with JavaScript, using the ROT.js library
baseurl: "/hero" # the subpath of your site, e.g. /blogurl: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jakofranko

# Build settings
markdown: kramdown
